"""Exclusive CAN signal to service mappings for domain HPC services."""

from __future__ import annotations

CAN_SIGNAL_SCHEMA_COUNT = 234

# mock_can_gateway is the generic publisher/ingress. It intentionally owns no subscriptions.
CAN_SIGNAL_SERVICE_MAPPINGS: dict[str, tuple[str, ...]] = {
    "powertrain_services": (
        "Vehicle.State.IgnitionState",
        "Vehicle.State.PowerMode",
        "Vehicle.State.Speed",
        "Vehicle.State.GearPosition",
        "Vehicle.State.DriveMode",
        "Vehicle.State.VehicleMoving",
        "Vehicle.Powertrain.MotorRPM",
        "Vehicle.Powertrain.MotorTorque",
        "Vehicle.Powertrain.MotorPower",
        "Vehicle.Powertrain.PowerLimitActive",
        "Vehicle.Powertrain.EnergyEfficiencyScore",
        "Vehicle.EVBattery.StateOfCharge",
        "Vehicle.EVBattery.StateOfHealth",
        "Vehicle.EVBattery.EstimatedRange",
        "Vehicle.EVBattery.ArrivalSOC",
        "Vehicle.EVBattery.Temperature",
        "Vehicle.EVBattery.Voltage",
        "Vehicle.EVBattery.Current",
        "Vehicle.EVBattery.PowerDraw",
        "Vehicle.EVBattery.LowBatteryWarning",
        "Vehicle.EVBattery.ThermalWarning",
        "Vehicle.EVBattery.DegradationRisk",
        "Vehicle.Charging.PortOpen",
        "Vehicle.Charging.CableConnected",
        "Vehicle.Charging.ChargingActive",
        "Vehicle.Charging.ChargingPower",
        "Vehicle.Charging.TimeToFull",
        "Vehicle.Charging.NearestChargerAvailable",
        "Vehicle.Charging.NearestChargerDistance",
        "Vehicle.Charging.QueueStatus",
        "Vehicle.Charging.PriceLevel",
        "Vehicle.Charging.FastChargingAvailable",
        "Vehicle.Fuel.Level",
        "Vehicle.Fuel.Range",
        "Vehicle.Fuel.LowFuelWarning",
        "Vehicle.Thermal.BatteryTemperature",
        "Vehicle.Thermal.MotorTemperature",
        "Vehicle.Thermal.BrakeTemperature",
        "Vehicle.Thermal.CoolingActive",
    ),
    "chassis_services": (
        "Vehicle.State.Acceleration",
        "Vehicle.Chassis.RoadRoughness",
        "Vehicle.Chassis.RoadFriction",
        "Vehicle.Chassis.PotholeDetected",
        "Vehicle.Chassis.StabilityControlActive",
        "Vehicle.Chassis.TractionControlActive",
        "Vehicle.Braking.BrakeHealth",
        "Vehicle.Braking.PadWearPercent",
        "Vehicle.Braking.HarshBrakingCount",
        "Vehicle.Braking.ABSActive",
        "Vehicle.Steering.Angle",
        "Vehicle.Steering.LateCorrectionsDetected",
        "Vehicle.Steering.FrequentCorrectionsDetected",
        "Vehicle.Suspension.Mode",
        "Vehicle.Suspension.Health",
        "Vehicle.Tires.FL.Pressure",
        "Vehicle.Tires.FR.Pressure",
        "Vehicle.Tires.RL.Pressure",
        "Vehicle.Tires.RR.Pressure",
        "Vehicle.Tires.FL.Temperature",
        "Vehicle.Tires.LowPressureWarning",
        "Vehicle.Tires.PunctureRisk",
    ),
    "adas_services": (
        "Vehicle.ADAS.LaneAssistActive",
        "Vehicle.ADAS.LaneDepartureWarning",
        "Vehicle.ADAS.AdaptiveCruiseActive",
        "Vehicle.ADAS.BlindSpotAlert",
        "Vehicle.ADAS.ForwardCollisionRisk",
        "Vehicle.ADAS.PedestrianRisk",
        "Vehicle.ADAS.SpeedLimit",
        "Vehicle.ADAS.SpeedLimitExceeded",
        "Vehicle.ADAS.SchoolZoneAhead",
        "Vehicle.ADAS.ComplexJunctionAhead",
        "Vehicle.ADAS.CameraStatus",
        "Vehicle.ADAS.RadarStatus",
        "Vehicle.ADAS.SensorBlocked",
        "Vehicle.ADAS.CameraConfidence",
        "Vehicle.ADAS.RadarConfidence",
    ),
    "body_services": (
        "Vehicle.State.VehicleLocked",
        "Vehicle.State.ParkedDuration",
        "Vehicle.Body.DriverDoorOpen",
        "Vehicle.Body.PassengerDoorOpen",
        "Vehicle.Body.RearLeftDoorOpen",
        "Vehicle.Body.RearRightDoorOpen",
        "Vehicle.Body.TrunkOpen",
        "Vehicle.Windows.FL.Open",
        "Vehicle.Windows.FR.Open",
        "Vehicle.Windows.RL.Open",
        "Vehicle.Windows.RR.Open",
        "Vehicle.Windows.SunroofOpen",
        "Vehicle.Lighting.HeadlightsOn",
        "Vehicle.Lighting.HighBeamOn",
        "Vehicle.Lighting.AmbientLightMode",
        "Vehicle.Cabin.Temperature",
        "Vehicle.Cabin.RearTemperature",
        "Vehicle.Cabin.NoiseLevel",
        "Vehicle.Cabin.SunExposure",
        "Vehicle.Cabin.CalmEnvironmentActive",
        "Vehicle.HVAC.FanSpeed",
        "Vehicle.HVAC.AutoModeActive",
        "Vehicle.HVAC.RecirculationActive",
        "Vehicle.HVAC.RearAirflowActive",
        "Vehicle.HVAC.FreshAirRecommended",
        "Vehicle.AirQuality.CabinCO2",
        "Vehicle.AirQuality.CabinAQI",
        "Vehicle.AirQuality.OutsideAQI",
        "Vehicle.Occupancy.DriverPresent",
        "Vehicle.Occupancy.FrontPassengerPresent",
        "Vehicle.Occupancy.RearLeftOccupied",
        "Vehicle.Occupancy.RearRightOccupied",
        "Vehicle.Occupancy.OccupantCount",
        "Vehicle.Occupancy.ChildDetected",
        "Vehicle.Occupancy.ChildSeatOccupied",
        "Vehicle.Occupancy.PetDetected",
        "Vehicle.Occupancy.PassengerSleeping",
        "Vehicle.Cargo.PhoneDetected",
        "Vehicle.Cargo.LaptopDetected",
        "Vehicle.Cargo.BagDetected",
        "Vehicle.Cargo.WalletDetected",
        "Vehicle.Cargo.GroceriesDetected",
        "Vehicle.Cargo.UmbrellaDetected",
        "Vehicle.Cargo.FrozenItemsDetected",
    ),
    "driver_monitoring_services": (
        "Vehicle.DriverMonitoring.DriverID",
        "Vehicle.DriverMonitoring.DriverName",
        "Vehicle.DriverMonitoring.FatigueScore",
        "Vehicle.DriverMonitoring.StressScore",
        "Vehicle.DriverMonitoring.AttentionScore",
        "Vehicle.DriverMonitoring.HeartRate",
        "Vehicle.DriverMonitoring.DriverMood",
        "Vehicle.DriverMonitoring.EyesOnRoad",
        "Vehicle.DriverMonitoring.HandsOnWheel",
        "Vehicle.DriverMonitoring.ContinuousDrivingDuration",
        "Vehicle.DriverBehavior.Style",
        "Vehicle.DriverBehavior.SmoothnessScore",
        "Vehicle.DriverBehavior.RapidAccelerationCount",
        "Vehicle.DriverBehavior.FrequentLaneChanges",
    ),
    "infotainment_services": (
        "Vehicle.Infotainment.MusicPlaying",
        "Vehicle.Infotainment.CurrentPlaylist",
        "Vehicle.Infotainment.PreferredPlaylist",
        "Vehicle.Infotainment.CallActive",
        "Vehicle.Infotainment.VolumeLevel",
        "Vehicle.Voice.MicrophoneActive",
        "Vehicle.Voice.LastDriverInputText",
        "Vehicle.Voice.LastDriverIntent",
        "Vehicle.Voice.LastDriverSentiment",
        "Vehicle.Voice.LastDriverUrgency",
        "Vehicle.Voice.LastDriverPreferenceUpdate",
        "Vehicle.Voice.DriverQuestionActive",
        "Vehicle.Voice.SpeechConfidence",
        "Vehicle.Voice.CompanionCurrentlySpeaking",
        "Vehicle.Voice.ConversationTurnId",
    ),
    "connectivity_services": (
        "Vehicle.State.Odometer",
        "Vehicle.State.TripDistance",
        "Vehicle.State.TripDuration",
        "Vehicle.State.CurrentLatitude",
        "Vehicle.State.CurrentLongitude",
        "Vehicle.State.Heading",
        "Vehicle.Navigation.Destination",
        "Vehicle.Navigation.DestinationCategory",
        "Vehicle.Navigation.ETA",
        "Vehicle.Navigation.DistanceRemaining",
        "Vehicle.Navigation.RouteType",
        "Vehicle.Navigation.AlternativeRouteAvailable",
        "Vehicle.Navigation.ScenicRouteAvailable",
        "Vehicle.Navigation.WrongDestinationDetected",
        "Vehicle.Traffic.Level",
        "Vehicle.Traffic.Increasing",
        "Vehicle.Traffic.AccidentAhead",
        "Vehicle.Traffic.RoadClosureAhead",
        "Vehicle.Weather.Current",
        "Vehicle.Weather.Ahead",
        "Vehicle.Weather.RainExpected",
        "Vehicle.Weather.RainExpectedInMinutes",
        "Vehicle.Weather.Visibility",
        "Vehicle.Weather.HailWarning",
        "Vehicle.Weather.SunGlareExpected",
        "Vehicle.Calendar.NextEventTitle",
        "Vehicle.Calendar.NextEventTime",
        "Vehicle.Calendar.NextEventLocation",
        "Vehicle.Calendar.MeetingCompleted",
        "Vehicle.Calendar.InterviewScheduled",
        "Vehicle.Calendar.PresentationTomorrow",
        "Vehicle.Calendar.SchoolPickupTime",
        "Vehicle.ParkingServices.DestinationParkingAvailability",
        "Vehicle.ParkingServices.AlternateParkingAvailable",
        "Vehicle.TravelServices.FlightStatus",
        "Vehicle.TravelServices.FlightDelayMinutes",
        "Vehicle.TravelServices.AirportTerminal",
        "Vehicle.TravelServices.SecurityWaitTime",
    ),
    "vehicle_health_services": (
        "Vehicle.Diagnostics.DTCActive",
        "Vehicle.Diagnostics.DTCCode",
        "Vehicle.Diagnostics.CriticalFault",
        "Vehicle.Diagnostics.ServiceDueDistance",
        "Vehicle.Diagnostics.BatteryWarning",
        "Vehicle.Diagnostics.BrakeWarning",
        "Vehicle.Diagnostics.TireWarning",
        "Vehicle.Diagnostics.ThermalWarning",
        "Vehicle.Diagnostics.VehicleHealthStatus",
        "Vehicle.Maintenance.ServiceDueSoon",
        "Vehicle.Maintenance.ServiceDueKm",
        "Vehicle.Maintenance.PredictiveMaintenanceAlert",
        "Vehicle.Security.DigitalKeyActive",
        "Vehicle.Security.AuthorizedUserPresent",
        "Vehicle.Security.UnauthorizedAccessDetected",
        "Vehicle.Security.CyberThreatLevel",
        "Vehicle.Security.AccessControlAlert",
        "Vehicle.Security.AccessControlLockdown",
        "Vehicle.Security.NetworkHealthStatus",
        "Vehicle.Security.SomeIPTrafficLevel",
        "Vehicle.Security.SomeIPAnomalyDetected",
    ),
    "uvi_companion_services": (
        "Vehicle.Personalization.FavoriteCoffeeBrand",
        "Vehicle.Personalization.FavoriteDrink",
        "Vehicle.Personalization.FavoriteGym",
        "Vehicle.Personalization.MusicProfile",
        "Vehicle.Personalization.LikesScenicRoutes",
        "Vehicle.Memory.RoutineDetected",
        "Vehicle.Memory.HabitPattern",
        "Vehicle.Memory.LifestylePattern",
        "Vehicle.Memory.FrequentDestination",
        "Vehicle.FoodServices.CoffeeNearby",
        "Vehicle.FoodServices.CoffeeDistance",
        "Vehicle.FoodServices.FavoriteCoffeeNearby",
        "Vehicle.FoodServices.RestaurantNearby",
        "Vehicle.UVI.ActiveEpisode",
        "Vehicle.UVI.ActiveScenarioTags",
        "Vehicle.UVI.ContextCompletenessScore",
        "Vehicle.UVI.InsightPriority",
        "Vehicle.UVI.RecommendedTone",
        "Vehicle.UVI.CompanionMode",
        "Vehicle.UVI.LastInsight",
        "Vehicle.UVI.LastCompanionMessage",
        "Vehicle.UVI.LastDriverResponse",
        "Vehicle.UVI.NextSuggestedAction",
        "Vehicle.UVI.SpeakNowRecommended",
        "Vehicle.UVI.DisplayOnDashboard",
        "Vehicle.UVI.RequiresDriverConfirmation",
    ),
}

CAN_SIGNAL_SERVICE_COUNTS: dict[str, int] = {
    service_name: len(signals)
    for service_name, signals in CAN_SIGNAL_SERVICE_MAPPINGS.items()
}


def all_subscribed_signals() -> tuple[str, ...]:
    """Return every schema signal assigned to exactly one domain HPC service."""
    return tuple(
        signal
        for signals in CAN_SIGNAL_SERVICE_MAPPINGS.values()
        for signal in signals
    )


def validate_subscription_map() -> None:
    """Raise ValueError when the exclusive subscription map is inconsistent."""
    signals = all_subscribed_signals()
    unique_signals = set(signals)
    if len(signals) != CAN_SIGNAL_SCHEMA_COUNT:
        raise ValueError(f"Expected {CAN_SIGNAL_SCHEMA_COUNT} assignments, got {len(signals)}")
    if len(unique_signals) != CAN_SIGNAL_SCHEMA_COUNT:
        duplicates = sorted(signal for signal in unique_signals if signals.count(signal) > 1)
        raise ValueError(f"Duplicate CAN signal mappings: {duplicates}")

